source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIImageView-AGCInitials_Example', :exclusive => true do
  pod 'UIImageView-AGCInitials', :path => '../'
end

target 'UIImageView-AGCInitials_Tests', :exclusive => true do
  pod 'UIImageView-AGCInitials', :path => '../'
  pod 'OCMock'
end
